[package]
name = "wolf_crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
log = "0.4.29"
env_logger = "0.11.8"
reqwest = "0.13.1"
html_parser = "0.7.0"
